/* tslint:disable */
/* eslint-disable */
/**
 * OpenApi specification - Georgi
 * OpenApi documentation for Spring security
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Georgi_Ivanov92@pm.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { PageSleeveResponse } from '../models';
// @ts-ignore
import type { Pageable } from '../models';
// @ts-ignore
import type { SaveSleeveRequest } from '../models';
// @ts-ignore
import type { SleeveResponse } from '../models';
/**
 * SleeveControllerApi - axios parameter creator
 * @export
 */
export const SleeveControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteSleeve: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteSleeve', 'id', id)
            const localVarPath = `/sleeves/delete/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {Pageable} pageable 
         * @param {number} warehouseId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllSleevesInWarehouse: async (pageable: Pageable, warehouseId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'pageable' is not null or undefined
            assertParamExists('getAllSleevesInWarehouse', 'pageable', pageable)
            // verify required parameter 'warehouseId' is not null or undefined
            assertParamExists('getAllSleevesInWarehouse', 'warehouseId', warehouseId)
            const localVarPath = `/sleeves/warehouse/{warehouseId}`
                .replace(`{${"warehouseId"}}`, encodeURIComponent(String(warehouseId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (pageable !== undefined) {
                for (const [key, value] of Object.entries(pageable)) {
                    localVarQueryParameter[key] = value;
                }
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} sleeveNumber 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSleeveNumber: async (sleeveNumber: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'sleeveNumber' is not null or undefined
            assertParamExists('getSleeveNumber', 'sleeveNumber', sleeveNumber)
            const localVarPath = `/sleeves/{sleeveNumber}`
                .replace(`{${"sleeveNumber"}}`, encodeURIComponent(String(sleeveNumber)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} sequence 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSleeveSequenceNumber: async (sequence: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'sequence' is not null or undefined
            assertParamExists('getSleeveSequenceNumber', 'sequence', sequence)
            const localVarPath = `/sleeves`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (sequence !== undefined) {
                localVarQueryParameter['sequence'] = sequence;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {SaveSleeveRequest} saveSleeveRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        saveSleeve: async (saveSleeveRequest: SaveSleeveRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'saveSleeveRequest' is not null or undefined
            assertParamExists('saveSleeve', 'saveSleeveRequest', saveSleeveRequest)
            const localVarPath = `/sleeves/save`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(saveSleeveRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id 
         * @param {{ [key: string]: any; }} requestBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateSleeve: async (id: number, requestBody: { [key: string]: any; }, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateSleeve', 'id', id)
            // verify required parameter 'requestBody' is not null or undefined
            assertParamExists('updateSleeve', 'requestBody', requestBody)
            const localVarPath = `/sleeves/update/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(requestBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SleeveControllerApi - functional programming interface
 * @export
 */
export const SleeveControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SleeveControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteSleeve(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteSleeve(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SleeveControllerApi.deleteSleeve']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {Pageable} pageable 
         * @param {number} warehouseId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllSleevesInWarehouse(pageable: Pageable, warehouseId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PageSleeveResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllSleevesInWarehouse(pageable, warehouseId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SleeveControllerApi.getAllSleevesInWarehouse']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} sleeveNumber 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSleeveNumber(sleeveNumber: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SleeveResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSleeveNumber(sleeveNumber, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SleeveControllerApi.getSleeveNumber']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} sequence 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSleeveSequenceNumber(sequence: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<SleeveResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSleeveSequenceNumber(sequence, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SleeveControllerApi.getSleeveSequenceNumber']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {SaveSleeveRequest} saveSleeveRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async saveSleeve(saveSleeveRequest: SaveSleeveRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SleeveResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.saveSleeve(saveSleeveRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SleeveControllerApi.saveSleeve']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} id 
         * @param {{ [key: string]: any; }} requestBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateSleeve(id: number, requestBody: { [key: string]: any; }, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SleeveResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateSleeve(id, requestBody, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SleeveControllerApi.updateSleeve']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SleeveControllerApi - factory interface
 * @export
 */
export const SleeveControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SleeveControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteSleeve(id: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteSleeve(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {Pageable} pageable 
         * @param {number} warehouseId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllSleevesInWarehouse(pageable: Pageable, warehouseId: number, options?: RawAxiosRequestConfig): AxiosPromise<PageSleeveResponse> {
            return localVarFp.getAllSleevesInWarehouse(pageable, warehouseId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} sleeveNumber 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSleeveNumber(sleeveNumber: number, options?: RawAxiosRequestConfig): AxiosPromise<SleeveResponse> {
            return localVarFp.getSleeveNumber(sleeveNumber, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} sequence 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSleeveSequenceNumber(sequence: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<SleeveResponse>> {
            return localVarFp.getSleeveSequenceNumber(sequence, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {SaveSleeveRequest} saveSleeveRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        saveSleeve(saveSleeveRequest: SaveSleeveRequest, options?: RawAxiosRequestConfig): AxiosPromise<SleeveResponse> {
            return localVarFp.saveSleeve(saveSleeveRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} id 
         * @param {{ [key: string]: any; }} requestBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateSleeve(id: number, requestBody: { [key: string]: any; }, options?: RawAxiosRequestConfig): AxiosPromise<SleeveResponse> {
            return localVarFp.updateSleeve(id, requestBody, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SleeveControllerApi - object-oriented interface
 * @export
 * @class SleeveControllerApi
 * @extends {BaseAPI}
 */
export class SleeveControllerApi extends BaseAPI {
    /**
     * 
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SleeveControllerApi
     */
    public deleteSleeve(id: number, options?: RawAxiosRequestConfig) {
        return SleeveControllerApiFp(this.configuration).deleteSleeve(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {Pageable} pageable 
     * @param {number} warehouseId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SleeveControllerApi
     */
    public getAllSleevesInWarehouse(pageable: Pageable, warehouseId: number, options?: RawAxiosRequestConfig) {
        return SleeveControllerApiFp(this.configuration).getAllSleevesInWarehouse(pageable, warehouseId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} sleeveNumber 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SleeveControllerApi
     */
    public getSleeveNumber(sleeveNumber: number, options?: RawAxiosRequestConfig) {
        return SleeveControllerApiFp(this.configuration).getSleeveNumber(sleeveNumber, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} sequence 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SleeveControllerApi
     */
    public getSleeveSequenceNumber(sequence: number, options?: RawAxiosRequestConfig) {
        return SleeveControllerApiFp(this.configuration).getSleeveSequenceNumber(sequence, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {SaveSleeveRequest} saveSleeveRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SleeveControllerApi
     */
    public saveSleeve(saveSleeveRequest: SaveSleeveRequest, options?: RawAxiosRequestConfig) {
        return SleeveControllerApiFp(this.configuration).saveSleeve(saveSleeveRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} id 
     * @param {{ [key: string]: any; }} requestBody 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SleeveControllerApi
     */
    public updateSleeve(id: number, requestBody: { [key: string]: any; }, options?: RawAxiosRequestConfig) {
        return SleeveControllerApiFp(this.configuration).updateSleeve(id, requestBody, options).then((request) => request(this.axios, this.basePath));
    }
}

