/**
 * OpenApi specification - Georgi
 * OpenApi documentation for Spring security
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Georgi_Ivanov92@pm.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import { type RequestArgs, BaseAPI } from '../base';
import type { PageSleeveResponse } from '../models';
import type { Pageable } from '../models';
import type { SaveSleeveRequest } from '../models';
import type { SleeveResponse } from '../models';
/**
 * SleeveControllerApi - axios parameter creator
 * @export
 */
export declare const SleeveControllerApiAxiosParamCreator: (configuration?: Configuration) => {
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteSleeve: (id: number, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @param {Pageable} pageable
     * @param {number} warehouseId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getAllSleevesInWarehouse: (pageable: Pageable, warehouseId: number, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @param {number} sleeveNumber
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getSleeveNumber: (sleeveNumber: number, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @param {number} sequence
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getSleeveSequenceNumber: (sequence: number, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @param {SaveSleeveRequest} saveSleeveRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    saveSleeve: (saveSleeveRequest: SaveSleeveRequest, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @param {number} id
     * @param {{ [key: string]: any; }} requestBody
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateSleeve: (id: number, requestBody: {
        [key: string]: any;
    }, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
};
/**
 * SleeveControllerApi - functional programming interface
 * @export
 */
export declare const SleeveControllerApiFp: (configuration?: Configuration) => {
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteSleeve(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     *
     * @param {Pageable} pageable
     * @param {number} warehouseId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getAllSleevesInWarehouse(pageable: Pageable, warehouseId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PageSleeveResponse>>;
    /**
     *
     * @param {number} sleeveNumber
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getSleeveNumber(sleeveNumber: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SleeveResponse>>;
    /**
     *
     * @param {number} sequence
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getSleeveSequenceNumber(sequence: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<SleeveResponse>>>;
    /**
     *
     * @param {SaveSleeveRequest} saveSleeveRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    saveSleeve(saveSleeveRequest: SaveSleeveRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SleeveResponse>>;
    /**
     *
     * @param {number} id
     * @param {{ [key: string]: any; }} requestBody
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateSleeve(id: number, requestBody: {
        [key: string]: any;
    }, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SleeveResponse>>;
};
/**
 * SleeveControllerApi - factory interface
 * @export
 */
export declare const SleeveControllerApiFactory: (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) => {
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteSleeve(id: number, options?: RawAxiosRequestConfig): AxiosPromise<void>;
    /**
     *
     * @param {Pageable} pageable
     * @param {number} warehouseId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getAllSleevesInWarehouse(pageable: Pageable, warehouseId: number, options?: RawAxiosRequestConfig): AxiosPromise<PageSleeveResponse>;
    /**
     *
     * @param {number} sleeveNumber
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getSleeveNumber(sleeveNumber: number, options?: RawAxiosRequestConfig): AxiosPromise<SleeveResponse>;
    /**
     *
     * @param {number} sequence
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getSleeveSequenceNumber(sequence: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<SleeveResponse>>;
    /**
     *
     * @param {SaveSleeveRequest} saveSleeveRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    saveSleeve(saveSleeveRequest: SaveSleeveRequest, options?: RawAxiosRequestConfig): AxiosPromise<SleeveResponse>;
    /**
     *
     * @param {number} id
     * @param {{ [key: string]: any; }} requestBody
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateSleeve(id: number, requestBody: {
        [key: string]: any;
    }, options?: RawAxiosRequestConfig): AxiosPromise<SleeveResponse>;
};
/**
 * SleeveControllerApi - object-oriented interface
 * @export
 * @class SleeveControllerApi
 * @extends {BaseAPI}
 */
export declare class SleeveControllerApi extends BaseAPI {
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SleeveControllerApi
     */
    deleteSleeve(id: number, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<void, any>>;
    /**
     *
     * @param {Pageable} pageable
     * @param {number} warehouseId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SleeveControllerApi
     */
    getAllSleevesInWarehouse(pageable: Pageable, warehouseId: number, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<PageSleeveResponse, any>>;
    /**
     *
     * @param {number} sleeveNumber
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SleeveControllerApi
     */
    getSleeveNumber(sleeveNumber: number, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<SleeveResponse, any>>;
    /**
     *
     * @param {number} sequence
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SleeveControllerApi
     */
    getSleeveSequenceNumber(sequence: number, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<SleeveResponse[], any>>;
    /**
     *
     * @param {SaveSleeveRequest} saveSleeveRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SleeveControllerApi
     */
    saveSleeve(saveSleeveRequest: SaveSleeveRequest, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<SleeveResponse, any>>;
    /**
     *
     * @param {number} id
     * @param {{ [key: string]: any; }} requestBody
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SleeveControllerApi
     */
    updateSleeve(id: number, requestBody: {
        [key: string]: any;
    }, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<SleeveResponse, any>>;
}
