/* tslint:disable */
/* eslint-disable */
/**
 * OpenApi specification - Georgi
 * OpenApi documentation for Spring security
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Georgi_Ivanov92@pm.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PageableObject } from './pageable-object';
// May contain unused imports in some cases
// @ts-ignore
import type { SleeveResponse } from './sleeve-response';
// May contain unused imports in some cases
// @ts-ignore
import type { SortObject } from './sort-object';

/**
 * 
 * @export
 * @interface PageSleeveResponse
 */
export interface PageSleeveResponse {
    /**
     * 
     * @type {number}
     * @memberof PageSleeveResponse
     */
    'totalElements'?: number;
    /**
     * 
     * @type {number}
     * @memberof PageSleeveResponse
     */
    'totalPages'?: number;
    /**
     * 
     * @type {PageableObject}
     * @memberof PageSleeveResponse
     */
    'pageable'?: PageableObject;
    /**
     * 
     * @type {boolean}
     * @memberof PageSleeveResponse
     */
    'first'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PageSleeveResponse
     */
    'last'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PageSleeveResponse
     */
    'size'?: number;
    /**
     * 
     * @type {Array<SleeveResponse>}
     * @memberof PageSleeveResponse
     */
    'content'?: Array<SleeveResponse>;
    /**
     * 
     * @type {number}
     * @memberof PageSleeveResponse
     */
    'number'?: number;
    /**
     * 
     * @type {SortObject}
     * @memberof PageSleeveResponse
     */
    'sort'?: SortObject;
    /**
     * 
     * @type {number}
     * @memberof PageSleeveResponse
     */
    'numberOfElements'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PageSleeveResponse
     */
    'empty'?: boolean;
}

