/* tslint:disable */
/* eslint-disable */
/**
 * OpenApi specification - Georgi
 * OpenApi documentation for Spring security
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Georgi_Ivanov92@pm.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RegisterUserResponse
 */
export interface RegisterUserResponse {
    /**
     * 
     * @type {number}
     * @memberof RegisterUserResponse
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof RegisterUserResponse
     */
    'firstName'?: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterUserResponse
     */
    'lastName'?: string;
    /**
     * 
     * @type {number}
     * @memberof RegisterUserResponse
     */
    'personalNumber'?: number;
    /**
     * 
     * @type {string}
     * @memberof RegisterUserResponse
     */
    'createdDate'?: string;
}

