/* tslint:disable */
/* eslint-disable */
/**
 * OpenApi specification - Georgi
 * OpenApi documentation for Spring security
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Georgi_Ivanov92@pm.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SaveSleeveRequest
 */
export interface SaveSleeveRequest {
    /**
     * 
     * @type {number}
     * @memberof SaveSleeveRequest
     */
    'sequenceNumber': number;
    /**
     * 
     * @type {number}
     * @memberof SaveSleeveRequest
     */
    'sleeveNumber': number;
    /**
     * 
     * @type {string}
     * @memberof SaveSleeveRequest
     */
    'design': string;
    /**
     * 
     * @type {string}
     * @memberof SaveSleeveRequest
     */
    'color': string;
    /**
     * 
     * @type {string}
     * @memberof SaveSleeveRequest
     */
    'manufacturer': string;
    /**
     * 
     * @type {string}
     * @memberof SaveSleeveRequest
     */
    'notes'?: string;
    /**
     * 
     * @type {number}
     * @memberof SaveSleeveRequest
     */
    'gear': number;
    /**
     * 
     * @type {number}
     * @memberof SaveSleeveRequest
     */
    'circumference': number;
    /**
     * 
     * @type {number}
     * @memberof SaveSleeveRequest
     */
    'slot': number;
    /**
     * 
     * @type {string}
     * @memberof SaveSleeveRequest
     */
    'manufactureDate': string;
    /**
     * 
     * @type {number}
     * @memberof SaveSleeveRequest
     */
    'width': number;
    /**
     * 
     * @type {number}
     * @memberof SaveSleeveRequest
     */
    'kmStand'?: number;
    /**
     * 
     * @type {string}
     * @memberof SaveSleeveRequest
     */
    'warehouse': string;
    /**
     * 
     * @type {string}
     * @memberof SaveSleeveRequest
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof SaveSleeveRequest
     */
    'type': SaveSleeveRequestTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof SaveSleeveRequest
     */
    'condition': SaveSleeveRequestConditionEnum;
}

export const SaveSleeveRequestTypeEnum = {
    Paint: 'PAINT',
    Flat: 'FLAT',
    Lack: 'LACK',
    NonFlat: 'NON_FLAT'
} as const;

export type SaveSleeveRequestTypeEnum = typeof SaveSleeveRequestTypeEnum[keyof typeof SaveSleeveRequestTypeEnum];
export const SaveSleeveRequestConditionEnum = {
    Damaged: 'DAMAGED',
    New: 'NEW',
    Used: 'USED'
} as const;

export type SaveSleeveRequestConditionEnum = typeof SaveSleeveRequestConditionEnum[keyof typeof SaveSleeveRequestConditionEnum];


