/* tslint:disable */
/* eslint-disable */
/**
 * OpenApi specification - Georgi
 * OpenApi documentation for Spring security
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Georgi_Ivanov92@pm.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { WarehouseResponse } from './warehouse-response';

/**
 * 
 * @export
 * @interface SleeveResponse
 */
export interface SleeveResponse {
    /**
     * 
     * @type {number}
     * @memberof SleeveResponse
     */
    'id'?: number;
    /**
     * 
     * @type {number}
     * @memberof SleeveResponse
     */
    'sequenceNumber'?: number;
    /**
     * 
     * @type {number}
     * @memberof SleeveResponse
     */
    'sleeveNumber'?: number;
    /**
     * 
     * @type {string}
     * @memberof SleeveResponse
     */
    'design'?: string;
    /**
     * 
     * @type {string}
     * @memberof SleeveResponse
     */
    'color'?: string;
    /**
     * 
     * @type {string}
     * @memberof SleeveResponse
     */
    'manufacturer'?: string;
    /**
     * 
     * @type {string}
     * @memberof SleeveResponse
     */
    'notes'?: string;
    /**
     * 
     * @type {number}
     * @memberof SleeveResponse
     */
    'gear'?: number;
    /**
     * 
     * @type {number}
     * @memberof SleeveResponse
     */
    'circumference'?: number;
    /**
     * 
     * @type {number}
     * @memberof SleeveResponse
     */
    'slot'?: number;
    /**
     * 
     * @type {string}
     * @memberof SleeveResponse
     */
    'manufactureDate'?: string;
    /**
     * 
     * @type {number}
     * @memberof SleeveResponse
     */
    'width'?: number;
    /**
     * 
     * @type {number}
     * @memberof SleeveResponse
     */
    'kmStand'?: number;
    /**
     * 
     * @type {WarehouseResponse}
     * @memberof SleeveResponse
     */
    'warehouse'?: WarehouseResponse;
    /**
     * 
     * @type {string}
     * @memberof SleeveResponse
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof SleeveResponse
     */
    'type'?: SleeveResponseTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof SleeveResponse
     */
    'condition'?: SleeveResponseConditionEnum;
}

export const SleeveResponseTypeEnum = {
    Paint: 'PAINT',
    Flat: 'FLAT',
    Lack: 'LACK',
    NonFlat: 'NON_FLAT'
} as const;

export type SleeveResponseTypeEnum = typeof SleeveResponseTypeEnum[keyof typeof SleeveResponseTypeEnum];
export const SleeveResponseConditionEnum = {
    Damaged: 'DAMAGED',
    New: 'NEW',
    Used: 'USED'
} as const;

export type SleeveResponseConditionEnum = typeof SleeveResponseConditionEnum[keyof typeof SleeveResponseConditionEnum];


