/* tslint:disable */
/* eslint-disable */
/**
 * OpenApi specification - Georgi
 * OpenApi documentation for Spring security
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Georgi_Ivanov92@pm.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface WarehouseResponse
 */
export interface WarehouseResponse {
    /**
     * 
     * @type {number}
     * @memberof WarehouseResponse
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof WarehouseResponse
     */
    'name'?: WarehouseResponseNameEnum;
}

export const WarehouseResponseNameEnum = {
    G: 'G',
    L3: 'L3',
    L1: 'L1'
} as const;

export type WarehouseResponseNameEnum = typeof WarehouseResponseNameEnum[keyof typeof WarehouseResponseNameEnum];


