/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/Sleeve/components/SleeveForm': RouteRecordInfo<'/Sleeve/components/SleeveForm', '/Sleeve/components/SleeveForm', Record<never, never>, Record<never, never>>,
    '/Sleeve/components/SleeveTable': RouteRecordInfo<'/Sleeve/components/SleeveTable', '/Sleeve/components/SleeveTable', Record<never, never>, Record<never, never>>,
    '/sleeves/': RouteRecordInfo<'/sleeves/', '/sleeves', Record<never, never>, Record<never, never>>,
    '/sleeves/create': RouteRecordInfo<'/sleeves/create', '/sleeves/create', Record<never, never>, Record<never, never>>,
    '/sleeves/edit/[id]': RouteRecordInfo<'/sleeves/edit/[id]', '/sleeves/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/sleeves/print': RouteRecordInfo<'/sleeves/print', '/sleeves/print', Record<never, never>, Record<never, never>>,
  }
}
